version: 2

jobs:
  build:
    docker:
    - image: circleci/php:7.2

    environment:
        MODULE_DIR: app/code/Eadesigndev/FullBreadcrumbs

    working_directory: ~/magento

    steps:
    - run:
          name: Setup test environment
          command: |
              sudo apt-get install -y libpng-dev
              sudo docker-php-ext-install gd
              sudo docker-php-ext-install bcmath
              sudo apt-get install -y libmcrypt-dev
              sudo docker-php-ext-install mcrypt
              sudo apt-get install -y libxslt-dev
              sudo docker-php-ext-install xsl
              sudo docker-php-ext-install pdo_mysql
              sudo docker-php-ext-install soap
    - run:
          name: Setup composer details
          command: |
              sudo composer self-update
              mkdir ~/.composer
              touch ~/.composer/auth.json
              echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_KEY}\",\"password\":\"${MAGENTO_SECRET}\"}}}" > ~/.composer/auth.json
              composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition . 2.3.0
              composer require eadesignro/module-eacore
              mkdir -p app/code/Eadesigndev/FullBreadcrumbs

    - checkout:
        path: app/code/Eadesigndev/FullBreadcrumbs

    - run:
        name: Install marketplace quality tools
        command: |
                composer create-project --repository=https://repo.magento.com magento/marketplace-eqp magento-coding-standard
                php magento-coding-standard/vendor/bin/phpcs --standard=magento-coding-standard/MEQP2/ruleset.xml  app/code/Eadesigndev/FullBreadcrumbs/Block/ app/code/Eadesigndev/FullBreadcrumbs/Helper/ app/code/Eadesigndev/FullBreadcrumbs/view/
                php vendor/bin/phpmd app/code/Eadesigndev/FullBreadcrumbs/Block/,app/code/Eadesigndev/FullBreadcrumbs/Helper/,app/code/Eadesigndev/FullBreadcrumbs/view/ text  dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
                php vendor/bin/phpunit app/code/Eadesigndev/Pdfgenerator/Test/ --config dev/tests/unit/phpunit.xml.dist